# Generated by Django 5.1.5 on 2025-02-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="last_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
